### ISSUE TITLE
Projeto abandonado?

### ISSUE THREAD

**Issue by OLDsheep** [mattbittencourt/MA-XML-V6.0-PTBR-MIUIBrasil#5]
Desde que as betas da MIUI 7 começaram a sair existem muitas coisas em inglês.

**Comment by mattbittencourt** [comment]
@OLDsheep , o projeto ainda está em andamento. A diferença é que, desde abril deste ano, estamos trabalhando com a tradução diretamente no site oficial http://en.miui.com. A tradução para português do Brasil está disponível em todos os dispositivos Xiaomi que possuam uma versão Global da ROM MIUI, seja ela a 6 ou 7. Estamos implementando um novo cronograma para atualizar também as ROMs não-oficiais, como é o caso das disponibilizadas no site xiaomi.eu, e acreditamos que durante a próxima semana estas mudanças já estejam em vigor por lá tambem.

**Comment by pauloturij** [comment]
precisam de colaboradores ?
estou disposto a ajudar.

**Comment by OLDsheep** [comment]
Opa, então beleza, é que tava estranhando o povo da xiaomi.eu usar a sua tradução e ela estar desatualizada.
Se estiver precisando de ajuda, to aqui também.

**Comment by mattbittencourt** [comment]
@OLDsheep @pauloturij vocês podem submeter suas colaborações diretamente em nossa nova plataforma de tradução, o crowdin. Este repositório será descontinuado e passaremos a atualizar colaborativamente lá! :)

http://traducao.miuirom.com.br
