### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by josuetds** [mattbittencourt/MA-XML-V6.0-PTBR-MIUIBrasil#6]
Olá! 
Eu não sei se estou postando no lugar correto, mas gostaria de reportar um bug que encontrei na rom da xiaomi.eu, como o bug não acontece em outro idioma, aparentemente tem relação com a tradução.
O bug é o seguinte: 
Sempre que vou em Configurações>Apps instalados> clico em Padrões, aparece a mensagem 'O configurações parou', pra mim consegui acessar as configurações de Apps Padrões só em outro idioma.

Se precisar de ajuda na tradução, pode contar comigo, eu nunca trabalhei em nenhum projeto do tipo, mas aprendo rápido.

Abraços.

**Comment by mattbittencourt** [comment]
@josuetds 

O projeto de tradução está sendo mantido agora em outro endereço, o traducao.miuirom.com.br
Através dele, iremos atualizar as strings no xiaomi.eu :)
